<?php
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $khodamNames = [
        // Original names
        "Khodam Si Petir Menari",
        "Khodam Si Angin Berbisik",
        "Khodam Si Harimau Melompat",
        "Khodam Si Kucing Tidur",
        "Khodam Si Naga Terbang",
        "Khodam Si Burung Bernyanyi",
        "Khodam Si Ular Menggeliat",
        "Khodam Si Gajah Berjalan",
        "Khodam Si Singa Mengaum",
        "Khodam Si Kuda Berlari",
        "Khodam Pikachu Ngereog",
        "Khodam Sempak Bolong",
        "Khodam Si Hantu Galau",
        "Khodam Si Tuyul Tertawa",
        "Khodam Si Kuntilanak Narsis",
        "Khodam Si Genderuwo Pemalu",
        "Khodam Si Pocong Berlari",
        "Khodam Si Setan Gundul",
        "Khodam Si Jenglot Melambai",
        "Khodam Si Lele Menyanyi",
        "Khodam Si Bebek Joget",
        "Khodam Si Ayam Terbang",
        "Khodam Si Kelinci Keren",
        "Khodam Si Domba Santai",
        "Khodam Si Kambing Guling",
        "Khodam Si Sapi Terbang",
        "Khodam Si Buaya Ngamuk",
        "Khodam Si Harimau Bernyanyi",
        "Khodam Si Singa Menari",
        "Khodam Si Ikan Lompat",
        "Khodam Si Udang Nyengir",
        "Khodam Si Kepiting Joget",
        "Khodam Si Kerang Ngompol",
        "Khodam Si Babi Hutan Ngamuk",
        "Khodam Si Gajah Menari",
        "Khodam Si Monyet Terbang",
        "Khodam Si Burung Gagak",
        "Khodam Si Lumba-lumba",
        "Khodam Si Beruang Kutub",
        "Khodam Si Singa Laut",
        "Khodam Si Gurita Pintar",
        "Khodam Si Kucing Manja",
        "Khodam Si Kelinci Madu",
        "Khodam Si Kuda Poni",
        "Khodam Si Panda Pemalu",
        "Khodam Si Rusa Lincah",
        "Khodam Si Srigala Menggigit",
        "Khodam Si Rubah Pintar",
        "Khodam Si Musang Nakal",
        "Khodam Si Banteng Perkasa",
        "Khodam Si Kuda Laut",
        "Khodam Si Kura-Kura Cepat",
        "Khodam Si Duyung Cantik",
        "Khodam Si Elang Perkasa",
        "Khodam Si Kucing Hoki",
        "Khodam Si Tikus Pintar",
        "Khodam Si Anjing Setia",
        "Khodam Si Serigala Berbulu Domba",
        "Khodam Si Kucing Tidur",
        "Khodam Si Koala Makan Daun",
        "Khodam Si Zebra Hitam Putih",
        "Khodam Si Badak Perkasa",
        "Khodam Si Burung Hantu",
        "Khodam Si Ikan Hiu",
        "Khodam Si Ulat Bulu",
        "Khodam Si Kupu-Kupu",
        "Khodam Si Belalang Sembah",
        "Khodam Si Lebah Pekerja",
        "Khodam Si Semut Berbaris",
        "Khodam Si Capung Menari",
        "Khodam Si Kunang-Kunang",
        "Khodam Si Tikus Got",
        "Khodam Si Burung Merak",
        "Khodam Si Burung Kolibri",
        "Khodam Si Kepompong",
        "Khodam Si Kumbang Tanduk",
        "Khodam Si Cicak Merayap",
        "Khodam Si Laba-Laba Menjaring",
        "Khodam Si Kelelawar Malam",
        "Khodam Si Buaya Darat",
        "Khodam Si Ular Sanca",
        "Khodam Si Ikan Cupang",
        "Khodam Si Udang Lobster",
        "Khodam Si Kepiting Rajungan",
        "Khodam Si Laba-Laba Tarantula",
        "Khodam Si Harimau Sumatera",
        "Khodam Si Elang Jawa",
        "Khodam Si Kuda Nil",
        "Khodam Si Anoa",
        "Khodam Si Burung Cenderawasih",
        "Khodam Si Ikan Koi",
        "Khodam Si Ayam Cemani",
        "Khodam Si Kucing Persia",
        "Khodam Si Anjing Chihuahua",
        "Khodam Si Burung Lovebird",
        "Khodam Si Monyet Ekor Panjang",
        "Khodam Si Bekantan",
        "Khodam Si Orangutan",
        "Khodam Si Harimau Putih",
        "Khodam Si Burung Merpati",
        "Khodam Si Tupai Terbang",
        "Khodam Si Hamster",
        "Khodam Si Kelinci Imut",

        // New names with themes
        "Khodam Hantu Jeruk",
        "Khodam Pocong Santai",
        "Khodam Kuntilanak Terbang",
        "Khodam Tuyul Lucu",
        "Khodam Genderuwo Gaul",
        "Khodam Hantu Kipas",
        "Khodam Hantu Payung",
        "Khodam Setan Kebo",
        "Khodam Jin Botak",
        "Khodam Dedemit Joget",
        "Khodam Ultraman Cilik",
        "Khodam Ultraman Botak",
        "Khodam Ultraman Tidur",
        "Khodam Ultraman Ngantuk",
        "Khodam Ultraman Beraksi",
        "Khodam Ultraman Santai",
        "Khodam Ultraman Hantu",
        "Khodam Ultraman Gaul",
        "Khodam Ultraman Joget",
        "Khodam Ultraman Bercanda",
        "Khodam Jokes Receh",
        "Khodam Ketawa Ngakak",
        "Khodam Serius Tapi Lucu",
        "Khodam Guyonan Koplak",
        "Khodam Humor Malam",
        "Khodam Guyonan Pagi",
        "Khodam Ketawa Histeris",
        "Khodam Lucu Banget",
        "Khodam Senyum Manis",
        "Khodam Tawa Bahagia",
        "Khodam Gelak Tawa",
        "Khodam Lawakan Segar",
        "Khodam Cerita Lucu",
        "Khodam Dongeng Kocak",
        "Khodam Plesetan Lucu",
        "Khodam Kata-Kata Konyol",
        "Khodam Meme Hidup",
        "Khodam Status WA Lucu",
        "Khodam Gurauan Garing",
        "Khodam Gurauan Gokil",
        "Khodam Lelucon Harian",
        "Khodam Stand-up Komedi",
        "Khodam Lawak Gila",
        "Khodam Hiburan Receh",
        "Khodam Ngakak Abis",
        "Khodam Konyol Tapi Seru",
        "Khodam Garing Tapi Lucu",
        "Khodam Humor Gila",
        "Khodam Ambatron",
        "Khodam Guyon Sopan"
    ];

    $name = $_POST['name'];
    $randomIndex = rand(0, count($khodamNames) - 1);
    $khodamName = $khodamNames[$randomIndex];

    echo json_encode(['khodam' => $khodamName]);
}
?>
